# Generated by Django 5.0.2 on 2025-05-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo_de_evento', models.CharField(max_length=50)),
                ('fecha_de_realizacion', models.DateField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('publico_objetivo', models.JSONField()),
                ('programa_educativo', models.CharField(max_length=50)),
                ('responsable_del_evento', models.CharField(max_length=100)),
                ('descripcion_breve', models.TextField(max_length=300)),
                ('cupo_max', models.PositiveIntegerField()),
            ],
        ),
    ]
