# Generated by Django 5.0.2 on 2025-05-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0005_alter_evento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_inicio',
        ),
    ]
