# Generated by Django 5.0.2 on 2025-05-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0006_remove_evento_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='publico_objetivo',
            field=models.CharField(max_length=100),
        ),
    ]
